services:

  lumiere.api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: lumiere.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:8080
    depends_on:
      - lumiere.database

  lumiere.database:

    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: lumiere.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@123
      - MSSQL_PID=Evaluation
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql
  
volumes:
  sql_data:
    